name: prepare
description: |
  Set up the environment with .tool-versions and caching, plus installing dependencies.
inputs:
  no-frozen-lockfile:
    description: 'Disable --frozen-lockfile when installing dependencies'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Collect versions
      shell: bash
      run: |
        echo "nodejs_version=$(cat .tool-versions | grep 'nodejs' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
        echo "pnpm_version=$(cat .tool-versions | grep 'pnpm' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"

    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: ${{ env.pnpm_version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ env.nodejs_version }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
          ${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.no-frozen-lockfile }}" == "true" ]; then
          pnpm install --no-frozen-lockfile
        else
          pnpm install --frozen-lockfile
        fi
