name: autofix
description: Automatically fix formatting issues
inputs:
  token:
    description: GitHub token
    required: true
  format-command:
    description: Command to run for formatting (default is 'pnpm format')
    required: false
    default: 'pnpm format'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        ref: "${{ github.event.pull_request.head.ref }}"

    - name: Prepare
      uses: steebchen/actions/prepare@main
      with:
        no-frozen-lockfile: true

    - name: Run format
      shell: bash
      run: ${{ inputs.format-command }}

    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        set -eux

        msg="chore(autofix): apply diff"
        last_commit_message=$(git log -1 --pretty=%B)

        if [[ -z "$last_commit_message" ]]; then
          echo "No last commit message found"
          exit 1
        fi

        # Skip processing if there's nothing to commit
        if git diff --exit-code; then
          echo "No changes to commit"
          exit 0
        fi

        # Prevent infinite loop by checking message
        if [[ "$last_commit_message" == "$msg" ]]; then
          git status
          git diff
          echo "Detected infinite loop, exiting"
          exit 1
        fi

        git config --local user.email "contact@luca-steeb.com"
        git config --local user.name "Luca Steeb (bot)"

        git add .
        git commit -m "$msg"

        REPO_REF=${{ github.event.pull_request.head.ref || github.ref_name }}
        git pull --rebase origin "$REPO_REF" || true
        git push origin "$REPO_REF"
