name: deploy
description: Deploy on CloudFlare Pages
inputs:
  CF_ACCOUNT_ID:
    description: CloudFlare Account ID
    required: true
  CF_ZONE_ID:
    description: CloudFlare Zone ID
    required: false
  CF_CACHE_API_KEY:
    description: CloudFlare Cache Purge Key
    required: false
  CF_DEPLOY_API_KEY:
    description: CloudFlare Deploy Key
    required: true
  SENTRY_AUTH_TOKEN:
    description: Sentry Auth Token for sourcemaps
    required: true
  NOTIFICATION_URL:
    description: Notification Webhook URL
    required: true
  GH_TOKEN:
    description: GitHub Account Token for creating deployments
    required: false
runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        if grep -q "next-on-pages" package.json; then
          pnpm next-on-pages
          echo "kind=next-on-pages" >> $GITHUB_ENV
        else
          if grep -q "opennext" package.json; then
            pnpm opennextjs-cloudflare build
          fi
          echo "kind=worker" >> $GITHUB_ENV
        fi
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.SENTRY_AUTH_TOKEN }}

    - name: Ensure flags
      shell: bash
      run: |
        set -eux

        if [ ! -f wrangler.json ]; then
          echo "error: no wrangler.json found"
          exit 1
        fi

        cat wrangler.json | jq -r '.upload_source_maps' | grep -q "true"
        cat wrangler.json | jq -r '.observability.enabled' | grep -q "true"

    - name: Deploy (Next.js)
      id: deploy_next
      if: env.kind == 'next-on-pages'
      uses: cloudflare/wrangler-action@v3.14.1
      with:
        apiToken: ${{ inputs.CF_DEPLOY_API_KEY }}
        accountId: ${{ inputs.CF_ACCOUNT_ID }}
        command: pages deploy .vercel/output/static/
        workingDirectory: "."

    - name: Upload Version (Worker)
      id: upload_worker
      if: env.kind == 'worker'
      uses: cloudflare/wrangler-action@v3.14.1
      with:
        apiToken: ${{ inputs.CF_DEPLOY_API_KEY }}
        accountId: ${{ inputs.CF_ACCOUNT_ID }}
        command: versions upload --message "${{ github.sha }} ${{ github.event.head_commit.message }}"
        workingDirectory: "."

    - name: Check Deployment URL
      shell: bash
      run: |
        set -eux

        url="${{ steps.deploy_next.outputs.deployment-url }}"
        if [ -z "$url" ]; then
          url="${{ steps.upload_worker.outputs.deployment-url }}"
        fi

        echo "Deployment URL: $url"
        echo "deployment_url=$url" >> $GITHUB_ENV

        # check if it returns success
        sleep 10

        curl -fvs -H "Cookie: bypass=true" "$url"

    - name: Deploy Version (Worker Main)
      id: deploy_worker_main
      if: env.kind == 'worker' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        set -ux

        # Extract the Version ID from the upload output
        VERSION_ID=$(echo "${{ steps.upload_worker.outputs.command-output }}" | grep "Version ID:" | awk '{print $NF}')
        
        set -e

        if [ -z "$VERSION_ID" ]; then
          echo "Error: Could not extract Version ID from upload output"
          exit 1
        fi

        echo "Deploying version: $VERSION_ID"

        # Deploy the specific version
        pnpm wrangler versions deploy $VERSION_ID -y --message "${{ github.sha }} ${{ github.event.head_commit.message }}"
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CF_DEPLOY_API_KEY }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CF_ACCOUNT_ID }}

    - name: Wait
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: bash
      run: sleep 10

    - name: Create GitHub Deployment
      if: inputs.GH_TOKEN != ''
      shell: bash
      run: |
        set -eux

        # Determine if this is a production or preview deployment
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          environment="production"
        else
          environment="preview"
        fi

        # Create the deployment using GitHub API
        response=$(curl -s -X POST \
          -H "Authorization: token ${{ inputs.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\
            \"ref\": \"${{ github.ref }}\",\
            \"environment\": \"$environment\",\
            \"auto_merge\": false,\
            \"required_contexts\": [],\
            \"description\": \"Deployment from GitHub Actions\",\
            \"transient_environment\": ${{ github.ref != 'refs/heads/main' }}\
          }" \
          https://api.github.com/repos/${{ github.repository }}/deployments)

        # Extract the deployment ID
        deployment_id=$(echo "$response" | jq -r '.id')

        if [ "$deployment_id" == "null" ]; then
          echo "Failed to create deployment:"
          echo "$response" | jq .
          exit 1
        fi

        echo "Created GitHub deployment with ID: $deployment_id"

        # Create a deployment status
        status_response=$(curl -s -X POST \
          -H "Authorization: token ${{ inputs.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\
            \"state\": \"success\",\
            \"environment\": \"$environment\",\
            \"environment_url\": \"${{ env.deployment_url }}\",\
            \"log_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\",\
            \"description\": \"Deployment completed successfully\"\
          }" \
          https://api.github.com/repos/${{ github.repository }}/deployments/$deployment_id/statuses)

        echo "Created deployment status: $status_response"

    - name: Purge Cloudflare Cache
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && inputs.CF_CACHE_API_KEY != '' && inputs.CF_ZONE_ID != ''
      shell: bash
      run: |
        set -eux
        res=$(curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "Authorization: Bearer $CF_CACHE_API_KEY" -d '{ "purge_everything": true }')
        if ! echo "$res" | jq -e '.success'; then
          echo "$res" | jq -r '.errors[]'
          exit 1
        fi
        echo "Cache purged"
      env:
        CF_CACHE_API_KEY: ${{ inputs.CF_CACHE_API_KEY }}
        CF_ZONE_ID: ${{ inputs.CF_ZONE_ID }}

    - name: Notify
      uses: steebchen/actions/notify@main
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        message: deploy success ✅
        webhook_url: ${{ inputs.NOTIFICATION_URL }}

    - name: Notify
      uses: steebchen/actions/notify@main
      if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        message: deploy failed ❌
        webhook_url: ${{ inputs.NOTIFICATION_URL }}
