name: auto-merge

on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "Metadata"
        id: metadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: "${{ inputs.token }}"

      - name: "Approve (minor & patch)"
        shell: bash
        id: approve
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ inputs.token }}

      - name: "Squash and merge"
        shell: bash
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ inputs.token }}
