name: auto-merge

on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Merge
        uses: ./automerge
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
